### PR TITLE
Sync hycom repos.

### PR DESCRIPTION
**Pull request by aerorahul**
This PR:
- adds action to sync hycom/hycom-src master branch
- updates README.

### CODE REVIEW

**Comment by aerorahul** [comment]
@BinLiu-NOAA @junwang-noaa 
I need one approval to continue.
If you don't want this functionality, please say so and we can let the fork be manually managed.

**Review by junwang-noaa — APPROVED** [review]

**Comment by BinLiu-NOAA** [comment]
Thanks @aerorahul!

This action will automatically sync the master branch under [NOAA-EMC fork of HYCOM-src](https://github.com/NOAA-EMC/HYCOM-src) with that under [the official HYCOM-src repo](https://github.com/HYCOM/HYCOM-src), right? The two branches will be identical in terms of both contents and commit logs, correct?

Thanks!

Bin

**Comment by aerorahul** [comment]
Yes @BinLiu-NOAA your assessment is correct.

No one should push directly to the NOAA-EMC fork of HYCOM-src `master` branch.  All PR's to `master` should go to the authoritative repo.
If this happens, `master` will diverge, the CI will fail, I will get an email message (, and I will be upset).

**Comment by BinLiu-NOAA** [comment]
> Yes @BinLiu-NOAA your assessment is correct.
> 
> No one should push directly to the NOAA-EMC fork of HYCOM-src `master` branch. All PR's to `master` should go to the authoritative repo.
> If this happens, `master` will diverge, the CI will fail, I will get an email message (, and I will be upset).

Thanks @aerorahul! This is exactly what I want as well. The two master branches should be identical.

**Review by BinLiu-NOAA — APPROVED** [review]
Looks good.

**Pull request merged**
